<?php

return [
    'roles' => [
        'owner' => [
            'transactions.view',
            'transactions.create',
            'transactions.update',
            'transactions.delete',
            'wallets.view',
            'wallets.create',
            'wallets.update',
            'wallets.delete',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'reports.view',
            'exports.pdf',
            'members.view',
            'members.manage',
            'settings.view',
            'settings.manage',
        ],
        'admin' => [
            'transactions.view',
            'transactions.create',
            'transactions.update',
            'transactions.delete',
            'wallets.view',
            'wallets.create',
            'wallets.update',
            'wallets.delete',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'reports.view',
            'exports.pdf',
            'members.view',
            'members.manage',
        ],
        'member' => [
            'transactions.view',
            'transactions.create',
            'transactions.update',
            'reports.view',
        ],
        'viewer' => [
            'transactions.view',
            'reports.view',
        ],
    ],
];
